
export const GET_CONTACTS="GET_CONTACTS";
export const SET_CURRENT_CONTACT="SET_CURRENT_CONTACT";
export const GET_CURRENT_CONVERSATION="GET_CURRENT_CONVERSATION";
export const SET_USER="SET_USER";




